# Generated by Django 5.2 on 2026-03-19 20:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostaway_reservation_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('channel', models.CharField(choices=[('direct', 'Direct'), ('airbnb', 'Airbnb'), ('booking', 'Booking'), ('vrbo', 'VRBO'), ('other', 'Other')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('confirmation_code', models.CharField(max_length=50, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.PositiveSmallIntegerField()),
                ('guests_count', models.PositiveSmallIntegerField(default=1)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('guest_notes', models.TextField(blank=True)),
                ('hostaway_raw_data', models.JSONField(blank=True, default=dict)),
                ('guest_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'guest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.property')),
            ],
            options={
                'ordering': ['-check_in_date'],
                'indexes': [models.Index(fields=['property', 'check_in_date', 'check_out_date'], name='reservation_propert_ffde57_idx'), models.Index(fields=['guest_user', 'status'], name='reservation_guest_u_21e8e6_idx'), models.Index(fields=['channel', 'status'], name='reservation_channel_e72a60_idx'), models.Index(fields=['check_in_date'], name='reservation_check_i_a5b8d0_idx')],
            },
        ),
    ]
