# Generated by Django 4.2.29 on 2026-03-20 19:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='extra_guest_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per additional guest beyond guests_included', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='guests_included',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of guests included in base price'),
        ),
    ]
