# Generated by Django 5.2 on 2026-03-19 20:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10, unique=True)),
                ('min_reservations', models.PositiveIntegerField(default=0)),
                ('min_referrals', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('early_checkin', models.BooleanField(default=False)),
                ('late_checkout', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('bonus_points_on_upgrade', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code_used', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_points_granted', models.PositiveIntegerField(default=0)),
                ('referred_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='reservations.reservation')),
                ('referred_user', models.OneToOneField(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_tier', models.CharField(max_length=10)),
                ('new_tier', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=200)),
                ('triggered_by', models.CharField(choices=[('reservation_completed', 'Reservation Completed'), ('referral_completed', 'Referral Completed'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire'), ('adjust', 'Adjust'), ('bonus', 'Bonus'), ('referral_bonus', 'Referral Bonus')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earn/bonus, negative for redeem/expire.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Only for earn transactions; 12 months after creation.', null=True)),
                ('points_remaining', models.IntegerField(default=0, help_text='Only for earn type; starts equal to points, decreases with FIFO redemption.')),
                ('balance_after', models.IntegerField(help_text="Guest's point balance after this transaction.")),
                ('description', models.CharField(max_length=200)),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest', 'transaction_type'], name='loyalty_poi_guest_i_849257_idx'), models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='idx_pt_expires_at_not_null')],
            },
        ),
    ]
