# Generated by Django 5.2 on 2026-03-19 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('smart_lock', 'Smart Lock'), ('thermostat', 'Thermostat'), ('noise_sensor', 'Noise Sensor')], max_length=20)),
                ('brand', models.CharField(choices=[('august', 'August'), ('schlage', 'Schlage'), ('nest', 'Nest'), ('ecobee', 'Ecobee'), ('minut', 'Minut')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('external_device_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('setup', 'Setup')], default='setup', max_length=20)),
                ('api_credentials', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_devices', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='NoiseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decibel_level', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threshold_exceeded', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('alert_sent_to_owner', models.BooleanField(default=False)),
                ('alert_sent_to_guest', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noise_alerts', to='reservations.reservation')),
                ('device', models.ForeignKey(limit_choices_to={'device_type': 'noise_sensor'}, on_delete=django.db.models.deletion.CASCADE, related_name='noise_alerts', to='domotics.smartdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LockAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('code_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_access_codes', to='reservations.reservation')),
                ('device', models.ForeignKey(limit_choices_to={'device_type': 'smart_lock'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='domotics.smartdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThermostatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('setpoint_change', 'Setpoint Change'), ('mode_change', 'Mode Change'), ('checkin_preset', 'Check-in Preset'), ('checkout_reset', 'Checkout Reset')], max_length=20)),
                ('temperature_set_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('guest', 'Guest'), ('owner', 'Owner')], max_length=10)),
                ('device', models.ForeignKey(limit_choices_to={'device_type': 'thermostat'}, on_delete=django.db.models.deletion.CASCADE, related_name='thermostat_logs', to='domotics.smartdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='smartdevice',
            index=models.Index(fields=['property', 'device_type'], name='domotics_sm_propert_dc0a7f_idx'),
        ),
    ]
